<?php echo $this->doctype(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="EN" lang="EN" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<title>Дүн мэдээ мэдээллийн үндэсний портал</title>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta http-equiv="imagetoolbar" content="no" />
    
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/layout.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/code.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/forms.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/styles/docs.min.css');?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/templatemo_style.css');?>
    
    <?php echo $this->headTitle();?>
    <?php echo $this ->headMeta();?>
    <?php $md = "/dun/public/modal/js/"; ?>
    <?php $js = "/dun/public/js/"; ?>
    
    <!--<script type='text/javascript' src="https://gist.github.com/makeusabrew/6327194.js"></script>-->
    <script type='text/javascript' src='<?php echo $js;?>countdown.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>countdown.min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.scrollTo-min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>jquery.localscroll-min.js'></script>
    <script type='text/javascript' src='<?php echo $js;?>bootstrap-tooltip.js'></script>

    <script src="<?php echo $js; ?>jquery.js"></script> 

    <script src="/dun/public/bootstrap/js/bootstrap.min.js"></script>
    <link href="/dun/public/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/dun/public/bootstrap/css/docs.min.css" rel="stylesheet">
    <link href="/dun/public/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <script type='text/javascript' src='<?php echo $md;?>bootstrap-modal.js'></script>
    
    <?php $editor = '/dun/public/ckeditor'; ?>
    <script type="text/javascript" src="<?php echo $editor; ?>/ckeditor.js"></script>
    <script type="text/javascript" src="<?php echo $editor; ?>/adapters/jquery.js"></script>
    <script type="text/javascript">
     $(function() {
                $('#textcontent' ).ckeditor();
            });
     var baseUrl = "http://localhost/dun/public";
    </script>

</head>
<body id = "top">
  
<div class = "body_header">
<div class = "left_dis">

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/index/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Нүүр хуудас</span></div></div></a></div></div>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/bukhchuud/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Бөхчүүд</span></div></div></a></div></div>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/barildaan/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Барилдаан</span></div></div></a></div></div>



<?php
          /*                  Хэрэглэгч нэвтрсэн үед             */
          if (Zend_Auth :: getInstance()->hasIdentity()) 
          {
              echo '<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/fantasy/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Фантази</span></div></div></a></div></div>';
          }
?>

<div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/other/index"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Бусад</span></div></div></a></div></div>

<div class = "right_dis">
<!--<div class="_5loo _42ef"><div class="_4-u2 _57mb _5j-9"><form action="#" method="get" role="search" onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)" id="u_0_b"><label class="_55r3 focus_target _5j-a child_was_focused" id="u_0_c"><img class="_55r5 img" src="https://fbstatic-a.akamaihd.net/rsrc.php/v2/yV/r/9wao2d_M9tx.png" alt="" width="16" height="16"><input type="text" class="inputtext _55r1 _5j-b _55r4 _55r2 _5f0v DOMControl_placeholder" name="query" placeholder="Дүн.мн - ээс хайх" id="u_0_7" aria-label="Search in docs"></label></form></div><div class="_51_-"><div class="_6a uiPopover" id="u_0_9"><a class="_p" href="#" aria-haspopup="true" aria-expanded="false" rel="toggle" role="button" id="u_0_a"><img class="img" src="https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash1/t5/187376_100002409768108_1745580880_q.jpg" alt=""></a></div></div></div>-->
<?php
          /*                  Хэрэглэгч нэвтрсэн үед             */
          if (Zend_Auth :: getInstance()->hasIdentity()) 
          {
              $uid = Zend_Registry::get('uid');
              echo '<div class = "user_loc"><ul>
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <img class="img" src="'.$this -> baseUrl().'/images/profile/adya.jpg" alt="" height = "28px" width = "28px"/>
                        
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="/dun/public/user/mypage/id/'.$uid.'">Миний хуудас</a></li>
                        <li><a href="#">Хувийн тохиргоо</a></li>
                        <li><a href="#">Үзүүлэлт</a></li>
                        <li><a href="/dun/public/authentication/logout">Гарах</a></li>
                      </ul>
                    </li>
                  </ul></div>';
          }
          else
          {
              echo '
              <div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/authentication/login"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Нэвтрэх</span></div></div></a></div></div>

              <div class="_6a _6e _5loj _5lok"><div class="_5lol"><a class="_5md9" href="/dun/public/authentication/register"><div class="_6a"><div class="_6a _6b" style="height:22px"></div><div class="_6a _6b"><span class="_5md5 _50f4 _50f7">Бүртгүүлэх</span></div></div></a></div></div>
  
              <div class="loc_right1">
              <a href="/dun/public/authentication/loginfacebook">
              <img src="'.$this -> baseUrl().'/images/facebook.jpg" height="22px" width="81px"></img>
              </a>
              </div>';
          }
?>
</div>
</div>  
</div>

<div class = "dis10"></div>
<div class="bodyHHH">

        <?php echo '<img src="'.$this -> baseUrl().'/images/header.jpg" height="100%" width="100%"></img>'; ?> 
</div>

<div class="bodyHH">
    <div class = "dis100"></div>
    <div class="body_left">
      <div class = "body_left_body"> 
        <?php echo $this->layout()->content; ?> 
      </div>
    </div>
    <div class="body_right">
        <div class = "reklam">
        <?php echo '<img src="'.$this -> baseUrl().'/images/huuhed.jpg" height="100%" width="100%"></img>'; ?>
        </div>
        <div class = "like-box">
            <div class = "like-box-header">
              Тавтай морилоно уу Дүн.мн
            </div>
            <iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2F%D0%94%D2%AF%D0%BD%D0%BC%D0%BD%2F574603322629339&amp;&amp;height=300&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=true&amp;appId=796259283733367" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100%; height:300px;" allowTransparency="true"></iframe>
        </div>
        <div class = "banner">
          <?php echo '<img src="'.$this -> baseUrl().'/images/huuhed1.jpg" height="100%" width="100%"></img>'; ?>
        </div>
        <div class = "banner">
          <?php echo '<img src="'.$this -> baseUrl().'/images/codeforces.png" height="100%" width="100%"></img>'; ?>
        </div>
    </div>

</div>

<div class="dis10"></div>

<div class="wrapper col7">
  <div id="copyright">
    <p class="center">
            school of imformation technology NUM @ 2014 
    </p>
  </div>
</div>
</body>
</html>